services:
  mongo:
    image: 'mongo:latest'
    volumes:
      - mongo:/data/db
    networks:
      - shared-mongo-net

  blair:
    build:
      context: .
    env_file:
      - .env.production
    volumes:
      - ./config.json:/usr/src/app/config.json
    networks:
      - shared-mongo-net

volumes:
  mongo:

networks:
  shared-mongo-net:
    external: true